[package]
name = "oizys"
version = "2025.1000.0"
edition = "2021"

[dependencies]
anstyle = "1.0.11"
anyhow = "1.0.99"
chrono = { version = "0.4.41", features = ["serde"] }
clap = { version = "4.5.46", features = ["derive"] }
clap_complete = "4.5.57"
color-eyre = { version = "0.6.5", default-features = false }
console = "0.16.0"
hostname = "0.4.1"
indicatif = "0.18.0"
nu-ansi-term = "0.50.1"
regex = "1.11.2"
reqwest = { version = "0.12.23", features = ["blocking", "json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
tracing = "0.1.41"
tracing-indicatif = "0.3.13"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
# tracing-tree = "0.4.0"
# fork adds support for configuring styling
tracing-tree = { git = "https://github.com/daylinmorgan/tracing-tree", version = "0.4.0" }
which = "8.0.0"


# until and if it supplants the nim oizys
[[bin]]
name = "oizys-rs"
path = "src/main.rs"

[features]
substituters = []

# [profile.release]
# strip = true
# lto = true
