#!/bin/sh
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
	xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
	xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
	xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
	xmodmap "$usermodmap"
fi


if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

[ -f ~/.xprofile ] && . ~/.xprofile

# taken from nixos wiki
if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
	eval "$(dbus-launch --exit-with-session --sh-syntax)"
fi

systemctl --user import-environment DISPLAY XAUTHORITY

if command -v dbus-update-activation-environment >/dev/null 2>&1; then
        dbus-update-activation-environment DISPLAY XAUTHORITY
fi

# eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
# export SSH_AUTH_SOCK

# $1 is xterm
# $2 is the wm arg passed to startx
# i.e. startx qtile

case $2 in
plasma)
	export DESKTOP_SESSION=plasma
	exec startplasma-x11
	;;
qtile)
	export DESKTOP_SESSION=qtile
	exec dbus-launch qtile start
	;;
*)
	export DESKTOP_SESSION=qtile
	exec dbus-launch qtile start
	;;
esac
