#!/usr/bin/env python3

import subprocess
from pathlib import Path


def gen_ls_colors(mode):
    return subprocess.check_output(
        [
            "nix",
            "run",
            "nixpkgs#vivid",
            "--",
            "-m",
            mode,
            "generate",
            "catppuccin-mocha",
        ],
        text = True
    ).strip()


ls_colors_24bit = gen_ls_colors("24-bit")
ls_colors_8bit = gen_ls_colors("8-bit")

t = f'''
#!/usr/bin/env zsh
# AUTOGENERATED DO NOT EDIT BY HAND
# See ~/.config/vivid/gen.py

if ! is-tty; then
  export LS_COLORS="{ls_colors_24bit}"
else
  export LS_COLORS="{ls_colors_8bit}"
fi
'''

(Path.home() / ".config/zsh/conf.d/lscolors.zsh").write_text(t)
