
[cursor.style]
blinking = "Never"
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "MonoLisa Nerd Font"

[window]
decorations = "None"
dynamic_padding = true
title = "Alacritty"

[window.dimensions]
columns = 90
lines = 45

[window.padding]
x = 10
y = 10

[general]
import = ["/home/daylin/.config/alacritty/catppuccin-mocha.toml"]
