#!/usr/bin/env zsh
# dogfen() {

parent=$(mktemp --directory --suffix=dogfen)
name=${1:-dogfen}
dogfen_file="$parent/$name.html"
echo '<!doctype html><script type=module src=https://esm.sh/dogfen></script><textarea style=display:none>' > $dogfen_file
[ -n "$1" ] && cat $1 >> $dogfen_file

# Open the temporary file in the default browser
xdg-open "$dogfen_file" # For Linux
# open "$TMPFILE"    # For macOS

# Clean up the temporary file after a delay
sleep 1
rm -r $parent

# }
