# originally adapted from https://github.com/azuwis/actions/tree/7236424fa0fdc8d82df7cd4bff831a9d2338ce9e/nix
name: Install Nix and setup cache
inputs:
  nix_conf:
    description: Extra nix.conf config
    default: |
      accept-flake-config = true
      experimental-features = nix-command flakes pipe-operator
      build-dir = /nix/var
      extra-substituters = https://nix-cache.dayl.in/oizys
      extra-trusted-public-keys = oizys:DSw3mwVMM/Y+PXSVpkDlU5dLwlORuiJRGPkwr5INSMc=
      stalled-download-timeout = 0
      download-attempts = 10
  attic_token:
    description: token to access attic cache
  hatchet-protocol:
    description: level passed on the nothing-but-nix
    default: 'cleave'

runs:
  using: composite
  steps:
    - name: Nothing but Nix
      uses: wimpysworld/nothing-but-nix@v5
      with:
        hatchet-protocol: ${{ inputs.hatchet-protocol }}

    - name: Wait for nothing-but-nix to get started to make some progress
      shell: bash
      run: sleep 5

    - name: Install Lix
      uses: samueldr/lix-gha-installer-action@latest
      with:
        extra_nix_config: ${{ inputs.nix_conf }}

    - name: Install and login to attic cache
      shell: bash
      run: |
        nix profile install "nixpkgs#attic-client"
        attic login oizys https://nix-cache.dayl.in "${{ inputs.attic_token}}"

    - name: "Show Nix Info"
      shell: bash
      run: nix run "nixpkgs#nix-info" -- -m

      # https://git.lix.systems/lix-project/lix/issues/545
      # https://ubuntu.com/blog/ubuntu-23-10-restricted-unprivileged-user-namespaces
    - name: "Revert ubuntu change that broke lix tests"
      shell: bash
      run: |
        sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
        sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
